### ISSUE TITLE
[Feature]: Context passing to prompt

### ISSUE THREAD

**Issue by nithinmuthukumar** [MrPicklePinosaur/shrs#109]
## What would you like to see added?

There is no way currently to pass context to prompt. Passing context would allow custom prompts to use runtime and ctx.

## Considerations

Passing data to prompt would be done through the set_right and set_left funcs, however that would require context to be passed through two more fns in line.rs and painter.rs

**Comment by MrPicklePinosaur** [comment]
Instead of using `set_right` and `set_left` funcs, the user can use runtime.state for generic user state data. For shell internal context, the prompt should be passed `Shell`, `Runtime` and `Context` in a future PR.

**Comment by MrPicklePinosaur** [comment]
resolved by #132
