### ISSUE TITLE
[Bug]: deleting characters and words with Ctrl + H and Ctrl + W not working 

### ISSUE THREAD

**Issue by kishooore** [MrPicklePinosaur/shrs#156]
I would like to report a bug regarding the inability to delete characters using Ctrl+H and words using Ctrl+W  in the shell. This feature, which is commonly supported in other shells, seems to be missing or not functioning as expected in the current implementation.

Steps to Reproduce:

1. Open the shell.
2. Start typing a command or a line of text.
3. Attempt to delete a character using Ctrl+H.
4. Notice that the character is not deleted as expected.
5. Similarly, attempt to delete a word using Ctrl+W.
6. Observe that the word is not deleted as expected.

**Comment by MrPicklePinosaur** [comment]
resolved by #162
