### ISSUE TITLE
Move `shrs` crate to `crates/shrs`

### ISSUE THREAD

**Issue by not-my-profile** [MrPicklePinosaur/shrs#233]
I think it would make sense to move the `shrs` crate to `crates/shrs`. As well as moving `shrs_example` under `examples`, so we would end up with the following structure:

* crates
   * shrs
       * examples
          * shrs_example
       * benches
       * src

What do you think about that idea?

**Comment by MrPicklePinosaur** [comment]
That does seem like a good idea, it will make the project structure a bit more consistent :+1:
