### ISSUE TITLE
[Bug]: why no history in example

### ISSUE THREAD

**Issue by locustbaby** [MrPicklePinosaur/shrs#272]
## What went wrong?
<img width="685" alt="image" src="https://github.com/MrPicklePinosaur/shrs/assets/21237232/11262bd6-45df-455e-bc72-db5c35bb2803">

**Comment by MrPicklePinosaur** [comment]
History is usually a builtin command, so each shell will have their own implementation. The shrs version of history is located in `crates/shrs_core/src/builtins/history.rs`, and it seems that the functionality hasn't been implemented yet.

I will open an issue for this, thanks!

**Comment by MrPicklePinosaur** [comment]
See #273
