### ISSUE TITLE
[Feature]: Implement history builtin

### ISSUE THREAD

**Issue by MrPicklePinosaur** [MrPicklePinosaur/shrs#273]
## What would you like to see added?

See `crates/shrs_core/src/builtins/history.rs`

Implement basic history querying and running of previous commands. The shell interface that is currently outlined is a bit different from bash, so it is worth thinking if we should stick to our own syntax for history builtin or mimic the bash history builtin.

**Comment by DavisRayM** [comment]
I'd like to pick this up if no one else is already working on it

**Comment by MrPicklePinosaur** [comment]
> I'd like to pick this up if no one else is already working on it

go for it!

**Comment by MrPicklePinosaur** [comment]
blocked on #284
