### ISSUE TITLE
[Bug]: `history_up` past history causes out-of-bounds error

### ISSUE THREAD

**Issue by Kyllingene** [MrPicklePinosaur/shrs#288]
## What went wrong?

Try the following with a basic shell:
```
> ls
...snip...
> [UP ARROW][UP ARROW]
```

On the second up, the program crashes (at `shrs_line/src/line.rs:706`) from `unwrap`ping a `None`. I'm not familiar enough with the architecture yet to know what causes this, but it doesn't happen unless there's at least one line of history.

Replacing the offending `unwrap` with an `if let` *did* stop the panic, but now you must press down twice to scroll past one line of history. I may do some digging on how `HistoryInd` works and try to fix this myself, but at the moment I'm simply too ignorant.

**Comment by MrPicklePinosaur** [comment]
funny that i never had this glaring issue since my history file got so long that it was rare that i would scroll to top of history :P
