### ISSUE TITLE
[Feature]: List installed plugins in help command

### ISSUE THREAD

**Issue by MrPicklePinosaur** [MrPicklePinosaur/shrs#297]
## What would you like to see added?

List any registered plugin, showing the plugin name as well as an relevant metadata in the help builtin.

This can be just added to the default output or added as a flag.

**Comment by locustbaby** [comment]
How about saving the list in an Env, maybe named as SHRS_PLUGINS?

**Comment by nithinmuthukumar** [comment]
That's a good idea, I'll make a separate issue for it. Think it's still a good idea for help to display this information, along with some other info that is displayed through help subcommands.
