### ISSUE TITLE
[Feature]: Add `type` builtin command

### ISSUE THREAD

**Issue by nithinmuthukumar** [MrPicklePinosaur/shrs#320]
## What would you like to see added?
A builtin that mirrors the which builtin command. Should also output if a command is a builtin one.

**Comment by AryanAb** [comment]
I think it is also a good idea to add the `type` command at some point in time. Given the short comings of the `which` command however, mainly with aliases, do we want to add both `which` and `type`, or just have the `type` command?

**Comment by nithinmuthukumar** [comment]
We can do something similar to `type` instead since they have very similar use cases. Didn't know about the issues with `which`.

**Comment by AryanAb** [comment]
> We can do something similar to `type` instead since they have very similar use cases. Didn't know about the issues with `which`.

In that case do we still want to call the command `which`? In case we want to name the command `type` then it would make sense to edit the tile of this issue.
