### ISSUE TITLE
Adding custom theme support in shrs

### ISSUE THREAD

**Issue by nithinmuthukumar** [MrPicklePinosaur/shrs#341]
Typically terminals use ANSI codes to represent colors. These colors are configured in the terminal settings or are read from a file. Shrs doesn't have the ability to change how the terminal itself represents ANSI codes, since different terminals have different ways of reading themes. 
Using crossterm::Color prints the ANSI code when formatting. This is dependent on the terminal theme so if it is changed the text color will also change.
Using crossterm::Color::RGB{} is a way to make the colors absolute. True color is adopted by most popular terminal applications but not all, ex. Mac built in terminal. [https://github.com/termstandard/colors](url)

To have custom theming that is not affected by terminal presets:
- Theme will have to use true color for all values. 

If this is implemented, shrs theme config will have no restrictions on the number of colors. Terminal theme configs are meant to work as ansi colors so shrs would have no need for that format. 

The other option is to forego custom themes and just use terminal presets and use absolute colors when necessary, not as part of a theme config.

**Comment by MrPicklePinosaur** [comment]
I think it will be nice to adopt a combination of the two if possible. If `crossterm::Color` is used it will fall back to whatever color was set by the terminal. If a specific RGB value is passed then it can just render that exact value. When specifying colors for the theme, users should have the abilitiy to choose between Color and RGB (should be easy with enum).
