### ISSUE TITLE
[Bug]: Running nvim in shrs uses a lot of cpu

### ISSUE THREAD

**Issue by nithinmuthukumar** [MrPicklePinosaur/shrs#349]
## What went wrong?
<img width="944" alt="Screenshot 2024-01-08 at 8 27 44 PM" src="https://github.com/MrPicklePinosaur/shrs/assets/33675303/cccc4540-ce76-4142-88ba-75b7e9bbad46">
Not sure what the reason is, will need further investigation

Once nvim is closed, it goes back to using very little resources

**Comment by MrPicklePinosaur** [comment]
interesting, i also randomly get really high cpu spikes for no reason. maybe the shell is busy looping for output or something when running an interactive command?

**Comment by rithikasilva** [comment]
Just to add, running `htop` and even `cmatrix` (needed to find something not super complicated that hijacks your terminal output lol) does this. Seems like it's output related, but not 100% sure.

**Comment by nithinmuthukumar** [comment]
I believe the issue is with `self.wait_for_job(job_id);` in job.rs. Removing the line and replacing with      `sleep(Duration::from_secs(30));` Seems to remove all performance issues. I thought it had to do with the duration of the program as it waits, but other long processes dont have any effects on performance, unless they take control of the terminal.
