### ISSUE TITLE
[Feature]: Ctrl-C when Typing a command should cancel it

### ISSUE THREAD

**Issue by nithinmuthukumar** [MrPicklePinosaur/shrs#379]
## What would you like to see added?
current typing ctrl-c just types c. Makes it so that Ctrl-c cancel the current line. A new line should appear and nothing should be saved to history or evaluated.

**Comment by MrPicklePinosaur** [comment]
i think this is not a very beginner issue, the process should be killed so it needs to interact with the job system

**Comment by nithinmuthukumar** [comment]
Im referring to when the line is being edited. In this case, it would simply be breaking in readline when ctrlc is received and creating the next line.
