### ISSUE TITLE
[Feature]: add plugin help to help builtin

### ISSUE THREAD

**Issue by MrPicklePinosaur** [MrPicklePinosaur/shrs#408]
## What would you like to see added?

Plugins themselves should be able to define a help message, which could then be referenced using
```
help plugin <plugin-name>
```

Reference https://github.com/MrPicklePinosaur/shrs/pull/405 for adding fields to plugin metadata and formatting

**Comment by rithikasilva** [comment]
Merged PR: https://github.com/MrPicklePinosaur/shrs/pull/410
