### ISSUE TITLE
[Bug]: Unable to set as terminal command

### ISSUE THREAD

**Issue by jmetz** [MrPicklePinosaur/shrs#496]
## What went wrong?

Running e.g. 

```
xfce4-terminal -H -x shrs
```
or equivalently
```
foot -H shrs
```

results in a panic:

```
thread 'main' panicked at crates/shrs_core/src/lang/posix_lang.rs:16:34:
called `Result::unwrap()` on an `Err` value: EPERM: Operation not permitted
```

Displaying the full backtrace doesn't reveal why `initialize_job_control` is failing here https://github.com/MrPicklePinosaur/shrs/blob/master/crates/shrs_core/src/lang/posix_lang.rs#L16C9-L16C31

Using e.g. a shell script to spawn `shrs` fixes the issue as there is a controlling shell process, so presumably this is related to having the terminal emulator as the direct parent process instead of a shell.

**Comment by jmetz** [comment]
I dug a bit further, and it turned out that the underlying culprit was trying to set the process group: 

```rust
    // Put ourselves in our own process group
    let shell_pgid = Pid::this();
    unistd::setpgid(shell_pgid, shell_pgid)?;  <---
```

https://github.com/MrPicklePinosaur/shrs/blob/master/crates/shrs_job/src/util.rs#L76C1-L76C46

I added a very simple hacky fix for now on my end - just ignoring if this fails :shrug: 
@MrPicklePinosaur - not sure if this relates to your `exec` issue (#489). 

Either way, presumably there's something else that should be done if we're launching without an outer shell... perhaps a `setsid` instead to create a new process group (don't know enough of the ins and outs to be sure here)?

**Comment by MrPicklePinosaur** [comment]
Appreciate the PR! A lot of the underlying os calls definitely stills needs a ton of work for sure.
