### ISSUE TITLE
[Feature]: builtin help function

### ISSUE THREAD

**Issue by MrPicklePinosaur** [MrPicklePinosaur/shrs#84]
## What would you like to see added?

It may be a bit intimidating to get started when using a brand new shell, even more so in the case of `shrs`, since each shell is built and configured differently by each person. A builtin help function can give a quick overview of what the current shell supports.

### Implementation Requirements

For the first version of the help builtin, it could just list out all the registered builtin commands.

**Comment by nithinmuthukumar** [comment]
Leave it to me, I got this 😎
